const provienceData = [
    {name: '新疆', en_name:'Xinjiang',value: 2},
    {name: '西藏', en_name:'Tibet',value: 1},
    {name: '内蒙古', en_name:'Inner Mongolia',value: 1},
    {name: '青海', en_name:'Qinghai',value: 1},
    {name: '四川', en_name:'Sichuan',value: 5},
    {name: '黑龙江', en_name:'Heilongjiang',value:4},
    {name: '甘肃', en_name:'Gansu',value: 1},
    {name: '云南', en_name:'Yunnan',value: 1},
    {name: '广西', en_name:'Guangxi',value: 1},
    {name: '湖南', en_name:'Hunan',value: 4},
    {name: '陕西', en_name:'Shaanxi',value: 8},
    {name: '广东', en_name:'Gunagdong',value: 4},
    {name: '吉林', en_name:'Jilin',value: 3},
    {name: '河北', en_name:'Hebei',value: 2},
    {name: '湖北', en_name:'Hubei',value: 7},
    {name: '贵州', en_name:'Guizhou',value: 1},
    {name: '山东', en_name:'Shandong',value: 3},
    {name: '江西', en_name:'Jiangxi',value: 1},
    {name: '河南', en_name:'Henan',value: 1},
    {name: '辽宁', en_name:'Liaoning',value: 4},
    {name: '山西', en_name:'Shanxi',value: 1},
    {name: '安徽', en_name:'Anhui',value: 3},
    {name: '福建', en_name:'Fujian',value: 2},
    {name: '浙江', en_name:'Zhejiang',value: 1},
    {name: '江苏', en_name:'Jaingsu',value: 11},
    {name: '重庆', en_name:'Chongqing',value: 2},
    {name: '宁夏', en_name:'Ningxia',value: 1},
    {name: '海南', en_name:'Hainan',value: 1},
    {name: '台湾', en_name:'Taiwan',value: 0},
    {name: '北京', en_name:'Beijing',value: 26},
    {name: '天津', en_name:'Tianjin',value: 3},
    {name: '上海', en_name:'Shanghai',value: 10},
    {name: '香港', en_name:'Hongkong',value: 0},
    {name: '澳门', en_name:'Macau',value: 0},
    {name: '南海诸岛', en_name:'Nanhai',value: 0},
];

export {provienceData}

